name: keyplay

description: "كيبورد تحدي - لعبة ثقافية عربية بفريقين ولوحة مفاتيح تفاعلية"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hexagon: ^0.2.0
  audioplayers: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.0
  media_store_plus: ^0.1.3
  share_plus: ^7.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/sounds/keyboard_click.mp3
    - assets/sounds/correct.mp3
    - assets/sounds/correct.ogg
    - assets/sounds/correct.wav
    - assets/sounds/correct.m4a
    - assets/sounds/wrong.mp3
    - assets/sounds/wrong.ogg
    - assets/sounds/wrong.wav
    - assets/sounds/wrong.m4a
    - assets/sounds/start-game.mp3
    - assets/sounds/win.mp3
    - assets/sounds/win.ogg
    - assets/sounds/win.wav
    - assets/sounds/win.m4a
    - assets/icon/
    - assets/backgrounds/telegram_bg.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 

fonts:
  - family: NotoColorEmoji
    fonts:
      - asset: fonts/NotoColorEmoji-Regular.ttf 